steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pomelo', '.']
images:
- 'gcr.io/$PROJECT_ID/pomelo'
options:
  logging: CLOUD_LOGGING_ONLY  # or NONE for no logs
timeout: '1800'
